src/App.tsx
src/components/ContentContainer/ContentContainer.tsx
src/components/Nav/Nav.tsx
src/components/Nav/components/SideBar.tsx

<br />
- header scroll 감지 후 보여주기 
- 스크롤 감지 후 transition 효과 추가 완료
- any타입 확실히 지정하기
- 불필요한 console.log 제거
<br />
1.  **header scroll 감지 후 보여주기**
- deltaY 속성 사용해서 scroll 상태 감지할 수 있는 기능 구현 완료
2. **스크롤 감지 후 transition 효과 추가 완료**
- 처음에는 visible / hidden으로 transition 속성 적용하려고 했는데 display 속성은 transition 을 적용할 수 없었다. 그래서 opacity-0으로 수정하여 transition을 적용했다.
3. **any타입 확실히 지정하기**
- e.deltaY에서의 e의 타입을 any로 지정했다가 확실히 하기 위하여 e: React.WheelEvent<HTMLDivElement>로 지정 완료
<br />
- 처음에는 visible / hidden으로 transition 속성 적용하려고 했는데 display 속성은 transition 을 적용할 수 없었다. 그래서 opacity-0으로 수정하여 transition을 적용했다.
- 우선 기능 구현을 위해 타입을 any로 했던 것들을 리뷰 받고 정확히 해야 겠다고 생각했다.
<br />

[Feat] header scroll 기능 구현 완료

---

src/hooks/useAxios.tsx

<br />
- useAxios custom hook 만들기
- 다른 component에서 유연하게 사용할 수 있게 만들기
<br />
**1. 다른 component에서 유연하게 사용할 수 있게 만들기**
- loading, error를 state로 만들어 axios의 상태를 알 수 있도록 하였다.
- data의 state를 만들어 axios의 값이 setData를 통해 data state에 담길 수 있도록 하였다.
- fetchData라는 함수를 만들어 axios를 실행시킬 수 있는 함수를 만들었다.
<br />
-custom hook을 처음 만들어봐서 처음에는 많이 어려웠지만 차근 차근 이해하고 여러 component에서 사용하다보니 여러 문제를 만나면서 보완해갈 수 있었다.
<br />

[Feat] useAxios hook 구현 완료

---

src/components/Footer/Footer.tsx

<br />
- 깔끔한 레이아웃
<br />
**1. tailwind CSS + daisy UI 라이브러리를 활용한 레이아웃 구현**
<br />
<br />

[Layout] footer 구현 완료

---

src/recoil/NumberState.tsx
src/recoil/ToggleState.tsx

<br />
1. 토글 및 카운터 상태 관리 atom 생성 (Like, Scrap)
2. 토글 및 카운터 상태 관리 selector 생성 (Like, Scrap)
<br />
1. 토글 및 카운터 상태 관리 atom 생성
- recoil 의 atomFamily, selectorFamily 를 이용, 매개변수를 사용해서 같은 속성을 갖는 여러 개의 atom / selector 만들 수 있도록 함
- 초기값을 undefined 로 설정해서 data 요청 전 / 후 구분 (data 요청 전에는 undefined, 요청 후에는 number)
<br />
2. 토글 및 카운터 상태 관리 selector 생성
- recoil 의 atomFamily, selectorFamily 를 이용, atom 과 selector 만들 때, toggle 매개변수랑 selector 매개변수는 똑같이 설정 (selector 에서 매개변수를 type 으로 받아 하나의 selector 로 좋아요 및 스크랩 상태 관리를 할 수 있게 함)
- toggleSelector / selector 의 set 함수 실행 시, 구독 중인 atom 값이 undefined 이면 매개변수 그대로 저장 / undefined 가 아니면 get 한 atom 값 (boolean) 반대로 저장
- numberSelector / selector 의 set 함수 실행 시, 구독 중인 atom 값이 undefined 이면 매개변수 그대로 저장 / undefined 가 아니면 같은 매개변수(type) 를 가진 toggleState 값이 true 일 때, 구독 중인 atom 값 …

[Feat] 토글 및 카운터 상태 관리 기능 구현

---

src/components/LikeScrapBtn/LikeScrapBtn.tsx

<br />
1. LikeScrapBtn 기능 구현
2. 비회원 alert 기능 구현
<br />
1. LikeScrapBtn 기능 구현
- 토글 및 카운터 atomFamily, SelectorFamily 이용하여 LikeScrapBtn 기능 구현
- LikeBtn 과 ScrapBtn 이 같은 컴포넌트로 렌더링 될 수 있게 함 / btnType, postType, postId 를 props 로 전달 받음 / atomFamily, selectorFamily 에 매개변수로 'btnType + postType + postId' 전달
- btnType 과 postType 에 따라 fetchUrl 이 동적으로 결정됨
- 버튼 클릭 시 POST 요청 후 response 에 따라 조건부 렌더링 / POST 성공 시, 카운터 setter 및 토글 setter 실행 / POST 실패 시 failedAlert('Failed')
<br />
2. 비회원 alert 기능 구현
- atom 으로 상태 관리되고 있는 currentUserIdState 을 구독하여 currentIdUserState 가 default 값인 경우, Btn 클릭 시 failedAlert('loginRequired') / alert 에 있는 Login 버튼 클릭하면 로그인 페이지로 이동
<br />
- props 로 전달받은 btnType 과 토글 상태에 따라 Icon 조건부 렌더링이 필요할 때! if 문을 사용하지 않고 객체로 만들면 가독성 좋게 코드를 작성할 수 있음 / data 가 들어오지 않았을 때, undefined 인 경우에도 렌더링 되도록 객체에 …

[Feat] LikeScrapBtn 기능 구현

---

src/components/LikeScrapBtn/LikeScrapBtn.tsx

<br />
1. btnSize 추가 
<br />
1. btnSize 추가
- LikeScrapBtn 을 컴포넌트로 렌더링할 때 btnType, postType, postId 뿐만 아니라 btnSize 를 props 로 전달하여 LikeScrapBtn 의 크기를 지정할 수 있게 함
<br />
<br />
<br />
<br />

[Feat] LikeScrapBtn btnSize 추가

---

src/components/Nav/Nav.tsx
src/components/Nav/components/SideBar.tsx

<br />
- 사이드바 메뉴 이벤트/멤버십 추가
<br />
1. 사이드바 메뉴 이벤트/멤버십 추가
- 클릭한 Side Bar의 id를 받아 각 페이지로 이동시키고 , 이동 완료되면 Side Bar state 사용해 숨김처리 완료
<br />

[Fix] 사이드바 메뉴 이벤트/멤버십 추가

---

public/data/eventInfo.json
src/components/ContentContainer/ContentContainer.tsx
src/pages/Event/EventDetail.tsx
src/pages/Event/EventList.tsx
src/pages/Event/components/EmailInput.tsx
src/pages/Event/components/EventInfo.tsx
src/pages/Event/components/EventSchedule.tsx
src/pages/Event/components/MovieInfo.tsx

<br />
- youtube player 컴포넌트 이벤트 페이지에 import 완료
- 영화 이벤트 mock데이터 수정 완료
<br />
1. youtube player 컴포넌트 이벤트 페이지에 import 완료
2.  영화 이벤트 mock데이터 수정 완료
- find 메소드 사용해서 객체 찾아내기 
-  찾는 id와 객체의 id가 같으면 해당 객체를 반환하는 로직에 대해서 많이 고민했었는데 , find메소드는 배열에서 주어진 조건을 만족하는 첫 번째 요소를 찾아 반환하기 때문에 쉽게 조건에 맞는 객체를 반환시킬 수 있었다.
```
const findEvent =
data !== null && data.find((item: EventData) => item.id === event);
const movieData =
data && data.find((item: any) => item.id === currentMovieId).movieInfo[0];
```

[Fix] 유튜브 플레이어 컴포넌트 import 완료

---

src/components/Comment/components/CommentInput.tsx
src/components/Comment/components/DropDownBtn.tsx
src/components/ContentContainer/ContentContainer.tsx

<br />
- 블로그 페이지 / 영화 상세 페이지 일때 요청 다르게 구현 완료
<br />
1. 블로그 페이지 / 영화 상세 페이지 일때 요청 다르게 구현 완료
- useLocation 사용해서 조건문으로 pathname에 따라 요청하는 url 다르게 변수에 할당하여 페이지 마다 요청 url 다르게 구현 완료
<br />
```
const commentAxiosUrl = location.pathname.includes('blogDetail')
? `${BASE_URL}/blog/postComment/${isEdit ? commentId : param.id}`
: `${BASE_URL}/movie/${commentId}/comments`;
```

[Fix] 블로그 페이지 / 영화 상세 페이지 일때 요청 다르게 구현 완료

---

src/pages/Blog/BlogDetail/BlogDetail.tsx
src/pages/Blog/BlogDetail/components/BlogHeader.tsx

<br />
1. DecodeToken 함수 적용
<br />
1. DecodeToken 함수 적용
- DecodeToken 함수 적용 및 sessionStorage.getItem('token') 으로 새로고침 후에 다시 token, currentId, currentNickname 저장
<br />
<br />
<br />
<br />

[Fix] DecodeToken 함수 적용

---

src/pages/Login/components/KakaoLogin.tsx
src/pages/Login/components/UserForm.tsx
src/pages/Login/components/UserInput.tsx

<br />
**1. 비밀번호 값을 다루는 input 창에, 복사/붙여넣기/자르기 기능을 막아 패스워드 오남용에 대한 보안을 높임**
**2. input 창에 값을 칠 때마다, 로그인 버튼이 반복적으로 깜빡이는 버그**
- 로그인 input 창에 걸어준 조건을 모두 만족할때'만', disabled 가 false 가 되도록 수정
- 만족하지 않을 때의 값을 삭제하고 && 연산자로 바꿔줌
**3. 로그인 버튼을 눌러도, 토큰 저장과 로그인이 안되는 버그**
- <form> 내 버튼 타입의 기본적인 submit 속성으로 인해, post request 가 두번씩 요청되어 크롬에서 막히는 버그가 있었음
- 그래서 로그인 버튼 타입을 button 으로 수정해주었더니 정상 작동
**4. input 을 관리하는 recoilState 가 새로고침이 아닌 이상 초기화가 되지 않아서, 로그아웃을 해도 input 창에 계속 로그인 정보가 남아있는 현상이 있었는데, 로그인 페이지 unmount 시, useResetRecoilState 를 사용하여 초기화되도록 수정**
**5. 로그인 시, 받아오는 데이터 타입 any => 구체적인 type 지정**
- <br />
- <br />
- <form> 태그 내의 버튼은 submit 속성을 기본적으로 가진다는 편함이 있지만, 크롬에서 post request 가 2번씩 가게되어 통신이 막힌다는 단점이 있다는 것을 알았다.
- 로그인은 정확한 코드와 로직, 그리고 토큰관리가 중요하다는 점을 몸소 느낀다. 
- <br />
- <br />

[Fix] 로그인 수정사항 반영

---

src/components/Comment/components/CommentInput.tsx
src/components/Comment/components/CommentList.tsx
src/components/Comment/components/DropDownBtn.tsx
src/pages/Blog/BlogDetail/BlogDetail.tsx
src/pages/MovieDetail/MovieDetail.tsx
src/recoil/BlogPostState.tsx
src/recoil/CommentState.tsx

<br />
- 무비페이지 / 블로그페이지 axios 다르게 요청할 수 있도록 수정 완료
<br />
1. 무비페이지 / 블로그페이지 axios 다르게 요청할 수 있도록 수정 완료

[Fix] 무비페이지 / 블로그페이지 axios 다르게 요청할 수 있도록 수정 완료

---

src/pages/Blog/BlogDetail/components/BlogHeader.tsx
src/pages/Blog/BlogPosting/components/PostBtn.tsx
src/recoil/BlogPostState.tsx

<br />
- 글 등록시 필수 항목 비어있으면 등록 불가능하게 에러 핸들링
- 유저가 썸네일 지정하지 않으면 기본 썸네일 올라갈 수 있게 지정 완료
<br />
1. 글 등록시 필수 항목 비어있으면 등록 불가능하게 에러 핸들링
- if문 사용해서 필수 항목 다 채워져있는지 각 항목별로 조건 걸어서 확인 후 비어있으면 모달창 띄워서 유저에게 알리고, return 해서 함수 종료시킴
<br />

[Fix] 글 등록시 필수 항목 비어있으면 등록 불가능하게 에러 핸들링 ( 썸네일 이미지 수정 필요 )

---

src/components/Alert/Modal.tsx
src/components/CopyBtn/CopyBtn.tsx
src/pages/MovieDetail/components/MovieDetailHeader.tsx

<br />
- CopyBtn 기능 구현
<br />
- 버튼 클릭 시 클립보드에 url 복사 / 성공 시 success alert / 실패 시 error alert
<br />
<br />
<br />
<br />

[Feat] CopyBtn 기능 구현

---

src/pages/MovieDetail/MovieDetail.tsx
src/pages/MovieDetail/components/ModalPlayer.tsx
src/pages/MovieDetail/components/MovieChat.tsx
src/pages/MovieDetail/components/MovieDetailBlog.tsx
src/pages/MovieDetail/components/MovieDetailBlogCard.tsx
src/pages/MovieDetail/components/MovieDetailHeader.tsx
src/pages/MovieDetail/components/TrailerPlaylist.tsx

<br />
- <br />
- <br />
- <br />
- <br />
- 수정 중
<br />

[Fix] 영화 디테일 페이지 버그 수정

---

src/components/LikeScrapBtn/LikeScrapBtn.tsx
src/pages/MovieDetail/components/MoviePlayer.tsx
src/pages/MovieDetail/components/RelatedVideo.tsx
src/recoil/MovieDetailState.tsx

<br />
- <br />
- <br />
- <br />
- <br />
- <br />

[Fix] LikeScrapBtn 토큰 및 alert 수정

---

src/pages/Blog/BlogMain/BlogMain.tsx
src/pages/Blog/BlogMain/components/BlogMainTop.tsx
src/pages/Blog/BlogMain/components/BlogRenderArticle.tsx
src/pages/Blog/BlogMain/components/BlogScrollArticle.tsx
src/pages/Blog/BlogMain/components/BlogSearchArticle.tsx
src/pages/Blog/BlogMain/components/BlogSpoToggle.tsx
src/recoil/MyBlogBtnState.tsx

수정 전: 
이전에 toggleSelector 로 관리했으나, 중복 클릭 시 값이 변동되어 데이터가 잘못 렌더링되었음
수정 후:
My blog 버튼 관리하는 새 recoil state 만들어서, 값 고정되게끔 수정 완료

[Fix] My blog 탭 중복 클릭될 때, 값 고정되어 데이터 변동되지 않도록 수정

---

src/components/Nav/components/Search.tsx
src/components/Nav/components/SearchModal.tsx
src/pages/Blog/BlogMain/components/Search.tsx
src/pages/Blog/BlogMain/components/SearchModal.tsx
src/recoil/SearchState.tsx

수정 전: toggleSelector 사용하여, 클릭만 하면 맘대로 검색창이 열리거나 닫힘
수정 후: 새 recoil state를 생성하여 boolean 값으로 설정 / 해당 요소 클릭 시에만 값이 고정되도록 수정

[Fix] 검색창 중복 클릭 시, 여닫아 지는 문제 수정

---

src/components/Nav/components/SearchModal.tsx
src/index.css
src/pages/Blog/BlogMain/BlogMain.tsx
src/pages/Blog/BlogMain/components/BlogArticle.tsx
src/pages/Blog/BlogMain/components/BlogDropDown.tsx
src/pages/Blog/BlogMain/components/BlogMainTop.tsx
src/pages/Blog/BlogMain/components/BlogRenderArticle.tsx
src/pages/Blog/BlogMain/components/BlogScrollArticle.tsx
src/pages/Blog/BlogMain/components/BlogSearchArticle.tsx
src/pages/Blog/BlogMain/components/BlogSpoToggle.tsx
src/pages/Blog/BlogMain/components/Search.tsx
src/pages/Blog/BlogMain/components/SearchModal.tsx
src/recoil/SearchState.tsx

<br />
- 모바일 / 태블릿 / 데스크탑 반응형 구현
<br />
- 모바일 버전을 기본 스타일로 설정하고, Tailwind CSS 문법으로 태블릿  / 데스크탑 버전까지 반응형 구현 완료
<br />
- 반응형 구현 머리아프다 ~~~ 나중엔 점차 똑똑하게 구현할 수 있길! 처음에 스타일을 줄 때, 깔끔하게 잘 줘야 반응형 때에도 덜 힘든 것 같다.
<br />

[Add] 블로그 메인페이지 반응형 구현 완료

---

src/components/Comment/components/CommentList.tsx

<br />
- 댓글 통신 메소드 post로 변경 
<br />
- 서버에서 기존 댓글 가져오기 메소드 get에서 post로 변경 요청하여 수정 완료
<br />

[Refactor] : 댓글 통신 메소드 post로 변경 완료

---

src/components/Skeleton/MovieDetailSkeleton.tsx
src/pages/MovieDetail/MovieDetail.tsx
src/pages/MovieDetail/components/MoviePlayer.tsx

<br />
-
<br />
-
<br />
-
<br />
-
<br />
-
<br />

[Feat] MoviePlayerSkeleton 반응형 기능 구현

---

src/index.css
src/pages/Blog/BlogMain/BlogMain.tsx
src/pages/Blog/BlogMain/components/BlogArticle.tsx
src/pages/Blog/BlogMain/components/BlogMainTop.tsx
src/pages/Blog/BlogMain/components/BlogSpoToggle.tsx
src/pages/Blog/BlogMain/components/Search.tsx
src/pages/Blog/BlogMain/components/SearchModal.tsx
tailwind.config.js

<br />
- 최소 사이즈 반응형 디테일 추가 구현
<br />
- 모바일 최소 사이즈를 360px로 정해서, 360px에 맞게 반응형 디테일 추가 구현
- 모바일 버전일때만, 검색창 닫기버튼 삭제하고, 검색하는 버튼으로 검색창 여닫을 수 있게 리팩토링
- 모바일 버전 레이아웃 , 데스크탑 버전 레이아웃 코드 따로 구현
- 사이즈에 따라 렌더링 되도록 style 을 hidden 혹은 flex 로 구현
<br />
- 다양한 모바일 사이즈가 존재하고 그것에 맞추기 위해서, 초기 기획과 컨벤션이 중요하다.
<br />

[Fix] 블로그 메인페이지 360px 반응형 추가 구현

---

src/components/ContentContainer/ContentContainer.tsx
src/components/Footer/Footer.tsx
src/index.css
src/pages/Login/Login.tsx
src/pages/Login/components/GoogleLoginBtn.tsx
src/pages/Login/components/KakaoLoginBtn.tsx
src/pages/Login/components/NaverLoginBtn.tsx
src/pages/Login/components/UserForm.tsx
src/pages/Login/components/UserInput.tsx
tailwind.config.js

<br />
- 로그인 페이지 반응형 스타일 구현 ( 모바일 / 태블릿 / 데스크탑 )
- 로그인 페이지 리팩토링
<br />
1. 반응형 스타일 구현
- 360px 이하 스타일을 기본 스타일로 주고, 그 위 viewport 사이즈에 따라 반응형 구현
- 동시에 Footer 반응형 구현
- tailwind.config.js 에 xxl 사이즈(min-width: 1500px)를 만들어, 데스크탑 반응형 좀 더 디테일하게 구현
2. 리팩토링
- 소셜로그인 버튼 공통스타일 index.css 에 추가하여 중복 스타일 코드 줄임
- 로그인 시, 이전에는 로그인 버튼을 클릭 시에만 로그인이 되었는데, onKeyDown 이벤트를 활용하여 enter 눌러도 submit 되도록 함수 추가 및 구현
<br />
-
<br />
-
<br />
-
<br />

[Fix] 로그인 페이지 반응형

---

src/pages/Blog/BlogPosting/components/Category.tsx
src/pages/Main/components/MainTab.tsx

<br />
- 블로그 editor에 글 입력할때마다 카테고리 post 요청되는 오류 수정
<br />
- 블로그 editor에 글 입력할때마다 카테고리 post 요청되는 오류 수정
- 카테고리 받아오는 useEffect 의존성배열에 blogpost 입력되어 있어서 오류 발생
- blogPost = 블로그 에디터에 입력되는 글
<br />

[Fix] 블로그 editor에 글 입력할때마다 카테고리 post 요청되는 오류 수정 완료

---

src/pages/Blog/BlogPosting/BlogPosting.tsx
src/pages/Blog/BlogPosting/components/Category.tsx
src/pages/Blog/BlogPosting/components/CustomEditor.tsx
src/pages/Blog/BlogPosting/components/Title.tsx
src/recoil/BlogPostState.tsx

<br />
1. 글 등록한 후에 다시 글쓰기 들어가면 수정 상태 데이터 들어오는 버그 수정
2. 수정 상태일 때 선택한 카테고리가 고정 안 되어 있는 버그 수정
<br />
- isEdit state 사용해서 수정상태일때만 등록한 데이터 보여질 수 있도록 수정 완료 
<br />

[Fix] 블로그 포스트 버그 수정

---

src/pages/Blog/BlogMain/components/BlogMainTop.tsx
src/pages/Signin/components/EmailInput.tsx

- BlogMainTop.tsx React.memo로 최적화
- EmailInput.tsx React.memo로 최적화

[Refactor] React.memo 활용하여 최적화

---

src/pages/Blog/BlogMain/components/BlogRenderArticle.tsx
src/pages/Blog/BlogMain/components/BlogScrollArticle.tsx
src/pages/Blog/BlogMain/components/BlogSearchArticle.tsx
src/pages/Blog/BlogMain/components/SearchModal.tsx
src/pages/Blog/BlogPosting/components/PostBtn.tsx

<br />
-
<br />
- 블로그 메인페이지 에서 검색기능 사용할 시, 검색아이콘을 클릭해야만 검색이 되었는데, 'Enter' 키 눌러도 검색되도록 구현
- 블로그 메인페이지 unmount 시, 검색된 데이터와 reset 되도록 recoilState 추가 / 검색창이 열려있으면, 닫히도록 구현
- 검색데이터 any type 에서 구체적인 type 지정
- 블로그 포스트 삭제 / 등록 후, 변화된 데이터에 따라 재렌더링 될 수 있도록 useEffect 추가
- 블로그 포스트 등록 시, 스포 여부 체크 안 되어있으면, 스포여부 체크해달라는 warningAlert 띄우기 추가
- 불필요한 주석 삭제
<br />
-
<br />
-
<br />
-
<br />

[Fix] 블로그 메인페이지 리팩토링

---

public/index.html
src/pages/Main/components/MainTab.tsx
src/pages/Main/components/MainTopRankCarousel.tsx
src/pages/Main/components/TabItems.tsx
src/pages/Main/components/TopRankItems.tsx

<br />
1. 메인 페이지 스타일 수정
<br />
1. 메인 페이지 스타일 수정
- 메인 페이지 카테고리 탭 UI 수정
- TabItems 및 TopRankItems 호버 스타일 수정
<br />
<br />
<br />
<br />

[Style] 메인 페이지 스타일 수정

---

src/components/CreatedAt/CreatedAt.tsx
src/pages/Blog/BlogMain/components/BlogArticle.tsx
src/pages/Blog/BlogMain/components/BlogRenderArticle.tsx
src/pages/Blog/BlogMain/components/BlogScrollArticle.tsx
src/pages/Blog/BlogMain/components/BlogSearchArticle.tsx

<br />
1. 블로그 작성 경과 시간 계산 함수 수정
<br />
1. 블로그 작성 경과 시간 계산 함수 수정
- displayCreatedAt, blogCreatedAt 두 개의 함수로 구현되어 있던 코드를 하나로 통합
<br />
<br />
<br />
<br />

[Refactor] 블로그 작성 경과 시간 계산 함수 (displayCreatedAt) 수정

---

src/pages/MovieDetail/components/ModalPlayer.tsx

<br />
1. ModalPlayer 내 MoviePlayer 반응형 기능 구현
<br />
1. ModalPlayer 내 MoviePlayer 반응형 기능 구현
- 스크린 중앙에 MoviePlayer 가 위치하므로 MoviePlayer (main) 과 달리 최소 height 가 필요하지 않음 / 스크린 크기가 바뀔 때마다 비율 16:9 유지하도록 height 계산하여 반응형 구현
<br />
<br />
<br />
<br />

[Feat] ModalPlayer 내 MoviePlayer 반응형 기능 구현
